site_name: pytest-pipesnap
site_description: A library for testing complicated data structures, doing snapshot testing and testing pipelines in an easier way. The package is structured around test cases stored in files, and outputs stored in files.
site_author: Martin Møldrup

theme: readthedocs

repo_url: https://github.com/martinmoldrup/pytest-pipesnap

pages:
- Home: index.md
